# =========================
# Puerto y contexto HTTP
# =========================
quarkus.http.port=8085
quarkus.banner.path=banner.txt

# Escuchar en todas las IPs
quarkus.http.host=192.168.1.132

# =========================
# Base de datos PostgreSQL
# =========================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:quarkus}
quarkus.datasource.password=${DB_PASS:quarkus}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:qurakuskafka}
quarkus.datasource.jdbc.schema=${DB_SCHEMA:kafka}

# =========================
# Hibernate
# =========================
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.sql-load-script=no-file

quarkus.http.cors=false
