-- Catálogo: Estados operativos de la caja del operador
INSERT INTO tomaturno.catalogo (id, nombre, descripcion, usuario_creacion, fecha_creacion, usuario_modificacion, fecha_modificacion, estado)
VALUES (3, 'ESTADOS_CAJA', 'Estados operativos de la caja del operador', 'sistema', NOW(), NULL, NULL, 1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO tomaturno.catalogodeta (idcatalogo, iddetalle, nombre, descripcion, usuario_creacion, fecha_creacion, usuario_modificacion, fecha_modificacion, estado)
VALUES
    (3, 1, 'ACTIVA',   'Caja abierta, disponible para recibir turnos', 'sistema', NOW(), NULL, NULL, 1),
    (3, 2, 'DESCANSO', 'Caja en pausa temporal',                       'sistema', NOW(), NULL, NULL, 1),
    (3, 3, 'CERRADA',  'Caja cerrada',                                 'sistema', NOW(), NULL, NULL, 1)
ON CONFLICT (idcatalogo, iddetalle) DO NOTHING;

-- Catálogo: Tipos de descanso del operador (extensible, se pueden agregar más filas después sin migración)
INSERT INTO tomaturno.catalogo (id, nombre, descripcion, usuario_creacion, fecha_creacion, usuario_modificacion, fecha_modificacion, estado)
VALUES (4, 'TIPOS_DESCANSO', 'Tipos de descanso del operador', 'sistema', NOW(), NULL, NULL, 1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO tomaturno.catalogodeta (idcatalogo, iddetalle, nombre, descripcion, usuario_creacion, fecha_creacion, usuario_modificacion, fecha_modificacion, estado)
VALUES
    (4, 1, 'BAÑO',    'Pausa para ir al baño', 'sistema', NOW(), NULL, NULL, 1),
    (4, 2, 'COMIDA',  'Pausa para comer',      'sistema', NOW(), NULL, NULL, 1),
    (4, 3, 'OTRO',    'Otro tipo de descanso', 'sistema', NOW(), NULL, NULL, 1)
ON CONFLICT (idcatalogo, iddetalle) DO NOTHING;

-- Historial de estados de caja del operador (para reportes: cuánto duró cada período).
-- fechafin NULL = fila vigente (estado actual del operador en esa sucursal).
CREATE TABLE IF NOT EXISTS tomaturno.usuarioestadocaja (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idusuario          bigint NOT NULL,
    idsucursal         bigint NOT NULL,
    idpuesto           bigint,
    idestadocaja       bigint NOT NULL,
    idtipodescanso     bigint,
    fechainicio        timestamp NOT NULL,
    fechafin           timestamp,
    usercreacion       varchar(255),
    fechacreacion      timestamp,
    usermodificacion   varchar(255),
    fechamodificacion  timestamp
);

-- Índice parcial: encontrar rápido el estado vigente (fechafin IS NULL) de un operador.
CREATE INDEX IF NOT EXISTS idx_usuarioestadocaja_actual ON tomaturno.usuarioestadocaja (idusuario, idsucursal) WHERE fechafin IS NULL;
